//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студенты
    {
        public int Id { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string Отчество { get; set; }
        public int КачалкаID { get; set; }
        public int СпортзалID { get; set; }
        public System.DateTime Время_записи { get; set; }
    
        public virtual Качалка Качалка { get; set; }
        public virtual Спортзал Спортзал { get; set; }
    }
}
